# Generated by Django 4.2.2 on 2023-06-29 12:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"verbose_name": "Цитата", "verbose_name_plural": "Цитаты"},
        ),
        migrations.RemoveField(
            model_name="message",
            name="author",
        ),
    ]
